/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InfoRouteImport } from './routes/info'
import { Route as LaCasaRouteImport } from './routes/la-casa'
import { Route as SmartTvRouteImport } from './routes/smart-tv'
import { Route as WifiRouteImport } from './routes/wifi'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoRoute = InfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => rootRouteImport,
} as any)
const LaCasaRoute = LaCasaRouteImport.update({
  id: '/la-casa',
  path: '/la-casa',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartTvRoute = SmartTvRouteImport.update({
  id: '/smart-tv',
  path: '/smart-tv',
  getParentRoute: () => rootRouteImport,
} as any)
const WifiRoute = WifiRouteImport.update({
  id: '/wifi',
  path: '/wifi',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/info': typeof InfoRoute
  '/la-casa': typeof LaCasaRoute
  '/smart-tv': typeof SmartTvRoute
  '/wifi': typeof WifiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/info': typeof InfoRoute
  '/la-casa': typeof LaCasaRoute
  '/smart-tv': typeof SmartTvRoute
  '/wifi': typeof WifiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/info': typeof InfoRoute
  '/la-casa': typeof LaCasaRoute
  '/smart-tv': typeof SmartTvRoute
  '/wifi': typeof WifiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/info' | '/la-casa' | '/smart-tv' | '/wifi'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/info' | '/la-casa' | '/smart-tv' | '/wifi'
  id: '__root__' | '/' | '/info' | '/la-casa' | '/smart-tv' | '/wifi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InfoRoute: typeof InfoRoute
  LaCasaRoute: typeof LaCasaRoute
  SmartTvRoute: typeof SmartTvRoute
  WifiRoute: typeof WifiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info': {
      id: '/info'
      path: '/info'
      fullPath: '/info'
      preLoaderRoute: typeof InfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/la-casa': {
      id: '/la-casa'
      path: '/la-casa'
      fullPath: '/la-casa'
      preLoaderRoute: typeof LaCasaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-tv': {
      id: '/smart-tv'
      path: '/smart-tv'
      fullPath: '/smart-tv'
      preLoaderRoute: typeof SmartTvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wifi': {
      id: '/wifi'
      path: '/wifi'
      fullPath: '/wifi'
      preLoaderRoute: typeof WifiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InfoRoute: InfoRoute,
  LaCasaRoute: LaCasaRoute,
  SmartTvRoute: SmartTvRoute,
  WifiRoute: WifiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
